[project]
name = "LFMSystem"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.3.0",
    "watchdog>=4.0.0",
    "pandas>=2.0.0",
    "click>=8.0.0",
    "loguru>=0.7.3",
    "pytest>=8.0.0"
]